# Generated by Django 4.0.2 on 2022-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='budget',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
